layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  hackerrank: joseph_pena
  # instagram: your_username
  # keybase: your_username
  linkedin: joseph-pena-quino 
  # mastodon: your_username
  # medium: your_username
  stackoverflow: 7911130 
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Linux
    web_url: https://www.linux.org/
    image_url: https://static-00.iconduck.com/assets.00/asstrnhe78x0

  - name: FreeRTOS 
    web_url: https://www.freertos.org/
    image_url: https://www.freertos.org/fr-content-src/uploads/2018/07/logo-1.jpg

  - name: C
    image_url: https://cdn.iconscout.com/icon/free/png-512/c-programming-569564.png

  - name: Raspberry
    web_url: https://www.raspberrypi.org/
    image_url: https://cdn.iconscout.com/icon/free/png-256/raspberry-pi-3-569254.png

  - name: TensorFlow
    web_url: https://www.tensorflow.org/?hl=es-419
    image_url: https://user-images.githubusercontent.com/13250741/64669187-33b55380-d47e-11e9-8bbf-c02a9d42f9a7.png

  - name: Python
    web_url: https://www.python.org/
    image_url: https://cdn3.iconfinder.com/data/icons/logos-and-brands-adobe/512/267_Python-512.png
